# Resmi PostGIS imajını kullan
FROM kartoza/pg-backup:16-3.4

# root kullanıcısına geçip güncelleme ve sudo kurulumu yapalım
USER root

# Paket listesini güncelle ve sudo'yu yükle
RUN apt-get update && \
    apt-get install -y sudo && \
    apt install nano  && \
    apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/Istanbul /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata
